/* Generated by Cython 3.0.2 */

#ifndef __PYX_HAVE__rtb_velocity_pytroller_logic
#define __PYX_HAVE__rtb_velocity_pytroller_logic

#include "Python.h"

#ifndef __PYX_HAVE_API__rtb_velocity_pytroller_logic

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
    #define __PYX_EXTERN_C extern "C++"
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int rtb_velocity_pytroller_logic(std::unordered_map<std::string,double> , std::unordered_map<std::string,double>  &, std::vector<int>  &, struct rtb_velocity_pytroller::Params);

#endif /* !__PYX_HAVE_API__rtb_velocity_pytroller_logic */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initrtb_velocity_pytroller_logic(void);
#else
/* WARNING: Use PyImport_AppendInittab("rtb_velocity_pytroller_logic", PyInit_rtb_velocity_pytroller_logic) instead of calling PyInit_rtb_velocity_pytroller_logic directly from Python 3.5 */
PyMODINIT_FUNC PyInit_rtb_velocity_pytroller_logic(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"rtb_velocity_pytroller_logic\", PyInit_rtb_velocity_pytroller_logic) instead of calling PyInit_rtb_velocity_pytroller_logic directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"rtb_velocity_pytroller_logic\", PyInit_rtb_velocity_pytroller_logic) instead of calling PyInit_rtb_velocity_pytroller_logic directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"rtb_velocity_pytroller_logic\", PyInit_rtb_velocity_pytroller_logic) instead of calling PyInit_rtb_velocity_pytroller_logic directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_rtb_velocity_pytroller_logic_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_rtb_velocity_pytroller_logic() __PYX_WARN_IF_PyInit_rtb_velocity_pytroller_logic_INIT_CALLED(PyInit_rtb_velocity_pytroller_logic())
#endif
#endif

#endif /* !__PYX_HAVE__rtb_velocity_pytroller_logic */
