controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rtb_velocity_pytroller:
      type: rtb_velocity_pytroller/RtbVelocityPytroller

rtb_velocity_pytroller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: velocity
    command_topic_name: ~/commands
    # command_topic_type: geometry_msgs/msg/Twist

    