controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rtb_velocity_pytroller:
      type: rtb_velocity_pytroller/RtbVelocityPytroller

rtb_velocity_pytroller:
  ros__parameters:
    interface_full_names:
      - shoulder_pan_joint/position
      - shoulder_lift_joint/position
      - elbow_joint/position
      - wrist_1_joint/position
      - wrist_2_joint/position
      - wrist_3_joint/position
    command_topic_name: ~/commands
    command_topic_type: geometry_msgs/msg/Twist
